name: tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  tests:

    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:10.4.12-bionic
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: nezuko-testing
          MYSQL_USER: nezuko
          MYSQL_PASSWORD: nezuko
        ports:
          - 33060:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    strategy:
      fail-fast: true
      matrix:
        php: [7.4]
        node: [12.15.0]

    name: PHP ${{ matrix.php }} - Node ${{ matrix.node }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: node-modules-${{ matrix.node }}-${{ hashFiles('package-lock.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@2.2.2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd
          coverage: none

      - name: Setup node.js environment
        uses: actions/setup-node@v1.4.2
        with:
          node-version: ${{ matrix.node }}

      - name: Install composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.dist', '.env');"

      - name: Generate key
        run: php artisan key:generate

      - name: Directory permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Build assets
        run: |
          npm install
          npm run dev

      - name: Execute tests
        run: ./vendor/bin/pest
        env:
          DB_PORT: ${{ job.services.mariadb.ports[3306] }}
          DB_DATABASE: nezuko-testing
          DB_USERNAME: nezuko
          DB_PASSWORD: nezuko

      - name: Run security test
        run: |
          git clone https://github.com/sensiolabs/security-checker.git
          cd security-checker
          composer install --no-interaction --no-progress
          php security-checker security:check ../composer.lock
